import Cocoa

/// 历史条目：文本 或 图片。
enum ClipItem {
    case text(String)
    case image(data: Data, type: NSPasteboard.PasteboardType, thumb: NSImage, size: NSSize)

    /// 列表里的一行预览文字。
    var preview: String {
        switch self {
        case .text(let s):
            return s.replacingOccurrences(of: "\n", with: " ")
        case .image(_, _, _, let size):
            return "图片  \(Int(size.width))×\(Int(size.height))"
        }
    }
    /// 文本内容（图片为 nil），用于搜索过滤。
    var searchText: String? {
        if case .text(let s) = self { return s }
        return nil
    }
}

/// @business_rule 剪贴板历史
/// 轮询 NSPasteboard 的 changeCount，记录文本与图片历史（去重、置顶、限量）。
/// - 跳过密码类（concealed/transient）内容；翻译期间挂起；只存内存，退出即清。
/// - 图片单张超过 8MB 跳过，避免内存膨胀。
final class ClipboardHistory {

    static let shared = ClipboardHistory()

    private(set) var items: [ClipItem] = []
    private var lastChangeCount = 0
    private var timer: Timer?

    var suspended = false

    private let maxImageBytes = 8 * 1024 * 1024
    private var maxItems: Int { max(10, AppConfig.shared.clipboardHistorySize) }

    private init() {}

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func clear() { items.removeAll() }

    /// 删除单条（文本按内容、图片按数据比对）。
    func remove(_ item: ClipItem) {
        items.removeAll { Self.same($0, item) }
    }

    static func same(_ a: ClipItem, _ b: ClipItem) -> Bool {
        switch (a, b) {
        case (.text(let x), .text(let y)): return x == y
        case (.image(let dx, _, _, _), .image(let dy, _, _, _)): return dx == dy
        default: return false
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if suspended { return }
        if !AppConfig.shared.clipboardEnabled { return }
        if isConcealed(pb) { return }

        // 优先记图片；没有图片再记文本
        if let (data, type) = readImage(pb), data.count <= maxImageBytes,
           let img = NSImage(data: data) {
            recordImage(data: data, type: type, image: img)
            return
        }
        if let str = pb.string(forType: .string) {
            let text = str.trimmingCharacters(in: .whitespacesAndNewlines)
            if !text.isEmpty { recordText(text) }
        }
    }

    private func recordText(_ text: String) {
        items.removeAll {
            if case .text(let s) = $0 { return s == text }
            return false
        }
        items.insert(.text(text), at: 0)
        trim()
    }

    private func recordImage(data: Data, type: NSPasteboard.PasteboardType, image: NSImage) {
        items.removeAll {
            if case .image(let d, _, _, _) = $0 { return d == data }
            return false
        }
        let size = image.size
        items.insert(.image(data: data, type: type, thumb: thumbnail(image), size: size), at: 0)
        trim()
    }

    private func trim() {
        if items.count > maxItems { items.removeLast(items.count - maxItems) }
    }

    /// 生成 ~36pt 高的缩略图用于列表显示，原图 data 仍保留用于粘贴。
    private func thumbnail(_ image: NSImage) -> NSImage {
        let targetH: CGFloat = 36
        let s = image.size
        guard s.height > 0 else { return image }
        let scale = targetH / s.height
        let newSize = NSSize(width: max(1, s.width * scale), height: targetH)
        let t = NSImage(size: newSize)
        t.lockFocus()
        image.draw(in: NSRect(origin: .zero, size: newSize),
                   from: NSRect(origin: .zero, size: s),
                   operation: .copy, fraction: 1.0)
        t.unlockFocus()
        return t
    }

    private func readImage(_ pb: NSPasteboard) -> (Data, NSPasteboard.PasteboardType)? {
        for t in [NSPasteboard.PasteboardType.png, .tiff] {
            if let d = pb.data(forType: t) { return (d, t) }
        }
        return nil
    }

    private func isConcealed(_ pb: NSPasteboard) -> Bool {
        let types = pb.types?.map { $0.rawValue } ?? []
        let skip = ["org.nspasteboard.ConcealedType",
                    "org.nspasteboard.TransientType",
                    "org.nspasteboard.AutoGeneratedType"]
        return types.contains { skip.contains($0) }
    }
}
